# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2017

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  归档: /archives
  分类: /categories
  关于: /about

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>Hello, I am Frost</p>
widget:
  Tags: true
  Categories: false

widget_custom:
    title: 圈子
    content: <ul class="social-list"> 
      <li class="social-item">
        <a href="mailto:xqtxyz@gmail.com" title="Email"><span class="iconfont icon-email"></span></a>
      </li>
      <li class="social-item">
        <a href="//github.com/qtxie" title="GitHub"><span class="iconfont icon-github"></span></a>
      </li>
      <li class="social-item">
        <a href="//space.bilibili.com/26105834" title="Bilibili"><span class="iconfont icon-bili"></span></a>
      </li>
      <li class="social-item">
        <a href="//www.x--x.red/atom.xml" title="RSS"><span class="iconfont icon-rss"></span></a>
      </li>
      </ul>

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: false

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname:


# ===========================================
# Version
# ===========================================
version: 1.1
